### ISSUE TITLE
Error displaying inline images

### ISSUE THREAD

**Issue by jaor** [emacs-w3m/emacs-w3m#66] opened 2019-08-13 21:11 UTC
Hi, i'm using emacs-w3m from melpa (latest version there) and since a week or so ago displaying inline images (via, e.g., I in an emacs-w3m buffer, or when i use it to render emails) is throwing an error with the message: 

           error in process sentinel: Wrong type argument: markerp, 3033 [6 times]

(the number 3033 varies with the page, i guess it's a position).  If i toggle again twice (I I) the image(s) appear fine, so it seems an error thrown only the first time right after downloading the images.

Thanks!

**Comment by yamaoka** [comment] 2019-08-19 07:20
I'm not sure if it is the cause of your problem but I found a bug in the w3m-external-view function and fixed it in the emacs-w3m git master. 　 Here is a diff:
```diff --git a/w3m.el b/w3m.el
index d8f1422e..3c6d8c80 100644
--- a/w3m.el
+++ b/w3m.el
@@ -7105,7 +7105,7 @@ command instead."
 	  (when (consp method)
 	    (let ((result))
 	      (setq method
-		    (dolist (elem (nreverse method) result)
+		    (dolist (elem method (nreverse result))
 		      (push (if (and (stringp elem)
 				     (string-match "\\`[\"']?%s[\"']?\\'"
 						   elem))
```
Could you spend some time to try this?

**Comment by jaor** [comment] 2019-08-19 14:51
hi,

thanks for the reply.  i've tried your patch, but unfortunately it
doesn't fix the problem that i'm encoutering.  i guess this is not
strange, because in my case the error is thrown when displaying inline
images inside emacs and i suppose that doesn't use external viewer.

many thanks nonetheless!

**Comment by yamaoka** [comment] 2019-08-19 23:47
> displaying inline images (via, e.g., I in an emacs-w3m buffer, or when i use it to render emails) is throwing an error with the message:
```
error in process sentinel: Wrong type argument: markerp, 3033 [6 times]
```
I see, sorry. 　 I tried w3m-20190819.701 from MELPA but I can see no problem to see images inline in an Emacs buffer. 　 Hmm. 　 Could you try to fetch a Lisp backtrace? 　 To do that:
```
M-x load-library RET w3m.el RET,
M-x toggle-debug-on-error RET,
perform something that arises the error in question,
and attach the contents of the *Backtrace* buffer as a file here.
```
Note that first you should do is to load w3m.el (i.e., a Lisp source), not w3m.elc.　If you get some human-unreadable byte-codes in a backtrace, it is better to load the other .el files (i.e., Lisp sources) and re-fetch a backtrace (you may delete all the w3m*.elc files before starting Emacs instead).　To retry to fetch a backtrace, type `C-]` to close the debugger in advance.

**Comment by jaor** [comment] 2019-08-20 00:53
Hi,

With the same version of w3m from melpa, and after loading the source, i
do:

  - Visit in a emacs-w3m window, with inline images off,  www.gnu.org
  - Press I (in the info keymap), or M-x w3m-toggle-inline-images

that gives the backtrace:

```
Debugger entered--Lisp error: (wrong-type-argument markerp 7125)
  marker-buffer(7125)
  (buffer-live-p (marker-buffer start))
  (if (buffer-live-p (marker-buffer start)) (progn (save-current-buffer (set-buffer (marker-buffer start)) (if image (if (equal url w3m-current-url) (progn (let ((inhibit-read-only t)) (w3m-insert-image start end image iurl)) (if w3m-force-redisplay (progn (sit-for 0))))) (let ((inhibit-read-only t)) (add-text-properties start end (append '(rear-nonsticky t) '(w3m-image-status off)) nil))) (set-buffer-modified-p nil))))
  (closure ((url . "https://www.gnu.org/") (end . #<marker at 1573 in *w3m*<25>>) (handler) (size) (image) (iurl . "https://www.gnu.org/graphics/fs-gang.png") (start . 7125) (allow-non-secure-images . t) (end . 6587) (cur-point . 272) (safe-regexp) (end-pos . 7125) (begin-pos . 1) (url) (no-cache) (status . off) t) (image) (if (buffer-live-p (marker-buffer start)) (progn (save-current-buffer (set-buffer (marker-buffer start)) (if image (if (equal url w3m-current-url) (progn (let ((inhibit-read-only t)) (w3m-insert-image start end image iurl)) (if w3m-force-redisplay (progn (sit-for 0))))) (let ((inhibit-read-only t)) (add-text-properties start end (append '(rear-nonsticky t) '(w3m-image-status off)) nil))) (set-buffer-modified-p nil)))) (set-marker start nil) (set-marker end nil))((image :type jpeg :data "\377\330\377\340\0\20JFIF\0\1\1\1\0H\0H\0\0\377\333\0C\0\3\2\2\3\2\2\3\3\3\3\4\3\3\4\5\10\5\5\4\4\5\n\7\7\6\10\f\n\f\f\13\n\13\13\15\16\22\20\15\16\21\16\13\13\20\26\20\21\23\24\25\25\25\f\17\27\30\26\24\30\22\24\25\24\377\333\0C\1\3\4\4\5\4\5..." :scale 1 :ascent center :background nil))
  w3m-process-sentinel(#<process w3m<10>> "finished\n")
```

The error is not specific of this web page: any page with images will
fail in a similar way (and also when displaying HTML emails in Gnus).
It happens for every image in the page that is toggled.

Please, let me know if you need any more information. Thanks.

**Comment by yamaoka** [comment] 2019-08-20 02:21
Thanks for the backtrace. 　 Please try this patch:
```
--- w3m.el~	2019-08-20 01:22:44.051093000 +0000
+++ w3m.el	2019-08-20 02:13:00.383971700 +0000
@@ -3782,8 +3782,8 @@
 				   (w3m-url-local-p iurl)
 				   (w3m-cache-available-p iurl))))
 		      (w3m-process-with-null-handler
-			(setq start (set-marker (make-marker) start))
-			(let ((end (set-marker (make-marker) end))
+			(let ((start (set-marker (make-marker) start))
+			      (end (set-marker (make-marker) end))
 			      (url w3m-current-url))
 			  (w3m-process-do
 			      (image
```
This is the cause probably. 　 So far I don't know why the error does not happen on me, though.

**Comment by jaor** [comment] 2019-08-20 02:34
That patch seems to indeed fix the problem for me... it's puzzling you
don't see it: maybe Emacs version? (mine is 27.0.50, directly compiled
from the git repository).

Thanks!

**Comment by yamaoka** [comment] 2019-08-20 03:45
Committed in the git master. 　 Thank you for verifying!

> So far I don't know why the error does not happen on me, though.

I run Emacs on Cygwin. 　 In that platform Emacs' asynchronous operations seem to be incomplete, that is, synchronous procedures will stop while an asynchronous process runs. 　 That is probably why the error does not happen on me. 　 On the other hand, in a system where synchronous procedures will progress even in the middle of an asynchronous process, the value of the lexical variable `start' will be overridden before it is referenced. 　 That is the reason you (and many others?) encountered the error.

**Closed by yamaoka** 2019-08-20 03:45 UTC
